### ISSUE TITLE
getSignedUrl is not a function in the injected s3 client

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-s3#15]
**Describe the bug**
getSignedUrl is not a function in the injected s3 client, though it should be available according to the docs [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property).

**Expected behavior**
getSignedUrl function should work as expected in the s3 client.

**Additional context**
This is a showstopper issue, and is breaking an already working functionality.

**Comment by ashutosh-bansal-2136** [comment]
Hi @akshatdubeysf ,
You can refer [this](https://github.com/aws/aws-sdk-js-v3/issues/456) if you are facing any issue.
